services:
  - type: web
    name: fixora-api
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      chmod +x start.sh
    startCommand: |
      export PYTHONPATH=$PYTHONPATH:$(pwd)
      gunicorn api_server:app --bind 0.0.0.0:$PORT --workers 4 --worker-class uvicorn.workers.UvicornWorker
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true 
